### ISSUE TITLE
Issue in showing the whole company on the tree chart

### ISSUE THREAD

**Issue by yalacat** [joaojmendes/React-Tree-Organization-Chart#1]
There is an issue in showing the whole company tree chart, it keeps on loading but the results are not retrieved. please advise.

**Comment by joaojmendes** [comment]
Hello,

There are a bug on loading when the display name attribute has one name only and the web part try to get the Initials....

Please download this package https://sitenanuvem-my.sharepoint.com/:u:/g/personal/joao_j_mendes_sitenanuvem_pt/EZ1AwxvDTa5NoDyJZwG6ZdoByYOCSD0FhbMfdpAOuDPOAA?e=LtWeew
and check if it is ok.

I will submit an PR to update the web part.

Thank you, and I'm sorry for the inconvenience...


________________________________

**Comment by yalacat** [comment]
Hi,

Thanks for the prompt reply. I tried with the new package, but the issue still exists.

**Comment by joaojmendes** [comment]
Can you please you check the browser console log ?  F12 on Browser -> console , and send me the logs ...

Thank you!


________________________________

**Comment by yalacat** [comment]
![image](https://user-images.githubusercontent.com/48783321/62039345-2a955d80-b215-11e9-8dc9-eeadd049bedd.png)
